FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN yarn cache clean
RUN yarn
RUN yarn global add ts-node
RUN yarn global add ts-node-dev 
RUN yarn global add typescript
COPY . .
CMD ["yarn", "run", "dev"]